language: php

matrix:
  include:
    - php: 5.3.3
      env:
        - DB=mysqli
        - SUIT=core,event
    - php: 5.3.3
      env:
        - DB=mysqli
        - SUIT=functional
    - php: 5.3
      env: 
        - DB=mysqli # MyISAM
        - SUIT=core,event
    - php: 5.3
      env: 
        - DB=mysqli # MyISAM
        - SUIT=functional
    - php: 5.4
      env: 
        - DB=mysqli
        - SUIT=core,event
    - php: 5.4
      env: 
        - DB=mysqli
        - SUIT=functional
    - php: 5.4
      env: 
        - DB=mysql
        - SUIT=core,event
    - php: 5.4
      env: 
        - DB=mysql
        - SUIT=functional
    - php: 5.4
      env: 
        - DB=mariadb
        - SUIT=core,event
    - php: 5.4
      env: 
        - DB=mariadb
        - SUIT=functional
    - php: 5.4
      env: 
        - DB=postgres
        - SUIT=core,event
    - php: 5.4
      env: 
        - DB=postgres
        - SUIT=functional
    - php: 5.4
      env: 
        - DB=sqlite3
        - SUIT=core,event
    - php: 5.4
      env: 
        - DB=sqlite3
        - SUIT=functional
    - php: 5.5
      env: 
        - DB=mysqli
        - SUIT=core,event
    - php: 5.5
      env: 
        - DB=mysqli
        - SUIT=functional
    - php: 5.6
      env: 
        - DB=mysqli
        - SUIT=core,event
    - php: 5.6
      env: 
        - DB=mysqli
        - SUIT=functional
    - php: hhvm
      env: 
        - DB=mysqli 
        - SUIT=core,event
    - php: hhvm
      env: 
        - DB=mysqli 
        - SUIT=functional
    - php: 7
      env: 
        - DB=mysqli
        - SUIT=core,event
    - php: 7
      env: 
        - DB=mysqli
        - SUIT=functional
  allow_failures:
    - php: hhvm
    - php: 7
  fast_finish: true

env:
  global:
    - EXTNAME="phpbbgallery"  # CHANGE name of the extension HERE
    - EXTSNIFF="phpbbgallery/core"
    - SNIFF="1"            # Should we run code sniffer on your code?
    - IMAGE_ICC="1"        # Should we run icc profile sniffer on your images?
    - EPV="1"              # Should we run EPV (Extension Pre Validator) on your code?
    - PHPBB_BRANCH="3.1.x"

branches:
  only:
    - master
    - /^(3\.[1-9]|[4-9]\.\d)\.x$/

install:
  - cd core
  - composer install --dev --no-interaction --prefer-source
  - cd ..
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - cd ../phpBB3
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTSNIFF; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - phpBB/vendor/bin/phpunit --configuration phpBB/ext/$EXTNAME/travis/phpunit-$DB-travis.xml --bootstrap ./tests/bootstrap.php --group $SUIT
  - sh -c "if [ '$EPV' != '0' ] && [ '$TRAVIS_PHP_VERSION' = '5.3.3' ] && [ '$DB' = 'mysqli' ]; then phpBB/ext/$EXTSNIFF/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/core'; fi"
  - sh -c "if [ '$EPV' != '0' ] && [ '$TRAVIS_PHP_VERSION' = '5.3.3' ] && [ '$DB' = 'mysqli' ]; then phpBB/ext/$EXTSNIFF/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/acpcleanup'; fi"
  - sh -c "if [ '$EPV' != '0' ] && [ '$TRAVIS_PHP_VERSION' = '5.3.3' ] && [ '$DB' = 'mysqli' ]; then phpBB/ext/$EXTSNIFF/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/acpimport'; fi"
  - sh -c "if [ '$EPV' != '0' ] && [ '$TRAVIS_PHP_VERSION' = '5.3.3' ] && [ '$DB' = 'mysqli' ]; then phpBB/ext/$EXTSNIFF/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/exif'; fi"

